# Generated by Django 3.1.7 on 2021-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0002_auto_20210729_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='by_player',
            field=models.BooleanField(blank=True, null=True, verbose_name='temps de jeu défini par joueur ?'),
        ),
    ]
