# Generated by Django 3.1.7 on 2021-09-26 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0005_auto_20210926_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedgames',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addon',
            name='modified_at',
            field=models.FloatField(default=1632678907.7648287, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='game',
            name='modified_at',
            field=models.FloatField(default=1632678907.7648287, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='multiaddon',
            name='modified_at',
            field=models.FloatField(default=1632678907.7648287, verbose_name='Dernière modification'),
        ),
    ]
