# Generated by Django 3.1.7 on 2021-09-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0006_auto_20210926_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='modified_at',
            field=models.FloatField(default=1632679103.637799, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='game',
            name='modified_at',
            field=models.FloatField(default=1632679103.637799, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='multiaddon',
            name='modified_at',
            field=models.FloatField(default=1632679103.637799, verbose_name='Dernière modification'),
        ),
    ]
