# Generated by Django 3.1.7 on 2021-09-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludorecherche', '0007_auto_20210926_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedgames',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='addon',
            name='modified_at',
            field=models.FloatField(default=1632726581.7155323, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='game',
            name='modified_at',
            field=models.FloatField(default=1632726581.7155323, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='multiaddon',
            name='modified_at',
            field=models.FloatField(default=1632726581.7155323, verbose_name='Dernière modification'),
        ),
    ]
